import { v4 as uuidv4 } from "uuid";

const initData = [
  {
    task: "Buy groceries",
    description: "Get fruits, vegetables, and milk from the store",
    id: uuidv4(),
    isDone: true,
    createdDate: "08-08-25",
    dueDate: "05-07-25",
  },
  {
    task: "Finish homework",
    description: "Complete the math assignment and history reading",
    id: uuidv4(),
    isDone: false,
    createdDate: "14-08-25",
    dueDate: "06-09-25",
  },
  {
    task: "Go for a walk",
    description: "30-minute evening walk in the park",
    id: uuidv4(),
    isDone: false,
    createdDate: "18-08-25",
    dueDate: "08-09-25",
  },
  {
    task: "Call Mom",
    description: "Catch up with Mom over the phone",
    id: uuidv4(),
    isDone: true,
    createdDate: "20-08-25",
    dueDate: "12-09-25",
  },
  {
    task: "Pay electricity bill",
    description: "Make the online payment before due date",
    id: uuidv4(),
    isDone: false,
    createdDate: "11-08-25",
    dueDate: "15-09-25",
  },
  {
    task: "Read a book",
    description: "Continue reading current novel for 20 minutes",
    id: uuidv4(),
    isDone: false,
    createdDate: "16-08-25",
    dueDate: "18-09-25",
  },
  {
    task: "Clean the room",
    description: "Organize desk, fold clothes, and vacuum floor",
    id: uuidv4(),
    isDone: true,
    createdDate: "22-08-25",
    dueDate: "20-09-25",
  },
  {
    task: "Workout at gym",
    description: "Leg day workout - squats, lunges, and deadlifts",
    id: uuidv4(),
    isDone: false,
    createdDate: "19-08-25",
    dueDate: "23-09-25",
  },
  {
    task: "Prepare dinner",
    description: "Cook pasta with garlic bread",
    id: uuidv4(),
    isDone: true,
    createdDate: "15-08-25",
    dueDate: "26-09-25",
  },
  {
    task: "Check emails",
    description: "Read and reply to pending work and personal emails",
    id: uuidv4(),
    isDone: false,
    createdDate: "09-08-25",
    dueDate: "28-09-25",
  },
];
export { initData };
